
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from summary import summarizer
from Translate import translator
from dictionary import dictionary

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets2\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def ai_menu(parent):
    parent.destroy()
    root = Tk()

    root.title("AI Features")

    # Load the custom icon (use .ico for Windows or .png for other platforms)
    icon = PhotoImage(file="icon.png")  # For Linux/macOS, use PNG
    root.iconphoto(False, icon)
    
    root.geometry("326x187")
    root.configure(bg = "#070707")


    canvas = Canvas(
        root,
        bg = "#070707",
        height = 187,
        width = 326,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:summarizer(root),
        relief="flat"
    )
    button_1.place(
        x=25.0,
        y=122.0,
        width=268.0,
        height=42.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: dictionary(root),
        relief="flat"
    )
    button_2.place(
        x=25.0,
        y=73.0,
        width=268.0,
        height=40.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: translator(root),
        relief="flat"
    )
    button_3.place(
        x=25.0,
        y=22.0,
        width=268.0,
        height=43.0
    )
    root.resizable(False, False)
    root.mainloop()
