
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import filedialog,messagebox
import tkinter as tk
import os
from Sl_file_gui import Win2
import saveNames

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Function to browse and select folder
def browse_folder():
    folder_selected = filedialog.askdirectory()  # Opens file explorer to select a folder
    if folder_selected:  # If a folder is selected, update the entry widget
        folder_path.set(folder_selected)

# Function to validate the path and show it in a new window
def show_folder_path():
    path = folder_path.get()
    if os.path.isdir(path):  # Check if the path is a valid directory
        # # Create a new window to display the valid folder path
        # result_window = tk.Toplevel(window)
        # result_window.title("Selected Folder Path")
        # result_window.geometry("400x100")
        
        # label_result = tk.Label(result_window, text=f"Selected Folder Path:\n{path}", padx=10, pady=10)
        # label_result.pack()
        # print(path)
        saveNames.set_folder(path)
        Win2(window)
    else:
        messagebox.showerror("Invalid Path", "The folder path entered is invalid. Please enter a valid path.") 



window = Tk()
# Variable to store the folder path
folder_path = tk.StringVar()
# Create the root window for the popup
# window.overrideredirect(True)  # Remove window decorations (title bar, etc.)
# window.attributes('-topmost', True)  # Keep the window on top
window.title("Note It Up")

# Load the custom icon (use .ico for Windows or .png for other platforms)
icon = PhotoImage(file="icon.png")  # For Linux/macOS, use PNG
window.iconphoto(False, icon)

window.geometry("440x215")
window.configure(bg = "#070707")


canvas = Canvas(
    window,
    bg = "#070707",
    height = 215,
    width = 440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    220.0,
    87.0,
    image=image_image_1
)

canvas.create_text(
    71.0,
    30.0,
    anchor="nw",
    text="Enter the folder path you  want   to  create docx \nor\nEnter the location where the existing docx is present",
    fill="#FFFFFF",
    font=("Inter", 12 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    222.0,
    98.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    textvariable=folder_path,
    highlightthickness=0
)
entry_1.place(
    x=45.0,
    y=90.0,
    width=354.0,
    height=15.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=browse_folder,
    relief="flat"
)
button_1.place(
    x=317.0,
    y=124.0,
    width=77.0,
    height=23.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=show_folder_path,
    relief="flat"
)
button_2.place(
    x=182.0,
    y=176.0,
    width=77.0,
    height=26.0
)
window.resizable(False, False)
window.mainloop()
